# Column Names
CONST_SACO = 'SACO'
CONST_CLIENTE = 'CLIENTE'
ORI_CONST_DESC = 'DESCRIÇÃO DO TRABALHO'
CONST_DESC = 'DESCRIÇÃO'
CONST_QUANT = 'QUANT.'
ORI_CONST_SECTOR = 'SECTOR EM QUE ESTÁ'
CONST_SECTOR = 'SECTOR'
CONST_ESTADO = 'ESTADO'
ORI_CONST_URG = 'URGÊNCIA / OBSERVAÇÕES'
CONST_URG = 'URGÊNCIA / OBS.'
CONST_DATA_ENTR = 'DATA ENTREGA'

# Date Format
DATE_FORMAT = '%d/%m/%Y_%H:%M'

COLUMN_NAMES = [CONST_SACO, CONST_CLIENTE ,CONST_DESC, CONST_QUANT, CONST_SECTOR, CONST_ESTADO, CONST_URG, CONST_DATA_ENTR]
